// <auto-generated />
using System;
using AltTextBot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AltTextBot.Migrations
{
    [DbContext(typeof(AltTextBotDbContext))]
    [Migration("20260315174135_AddTrackedImages")]
    partial class AddTrackedImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AltTextBot.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubscriberDid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubscriberDid");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AltTextBot.Domain.Entities.FirehoseState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("LastTimeUs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("FirehoseStates");
                });

            modelBuilder.Entity("AltTextBot.Domain.Entities.Subscriber", b =>
                {
                    b.Property<string>("Did")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("LastScoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SubscribedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Did");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("AltTextBot.Domain.Entities.TrackedImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobCid")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("HasAlt")
                        .HasColumnType("boolean");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("PostAtUri")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("PostAtUri");

                    b.ToTable("TrackedImages");
                });

            modelBuilder.Entity("AltTextBot.Domain.Entities.TrackedPost", b =>
                {
                    b.Property<string>("AtUri")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("AllImagesHaveAlt")
                        .HasColumnType("boolean");

                    b.Property<int>("AltTextCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasImages")
                        .HasColumnType("boolean");

                    b.Property<int>("ImageCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriberDid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AtUri");

                    b.HasIndex("SubscriberDid", "CreatedAt");

                    b.ToTable("TrackedPosts");
                });

            modelBuilder.Entity("AltTextBot.Domain.Entities.TrackedImage", b =>
                {
                    b.HasOne("AltTextBot.Domain.Entities.TrackedPost", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostAtUri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("AltTextBot.Domain.Entities.TrackedPost", b =>
                {
                    b.HasOne("AltTextBot.Domain.Entities.Subscriber", "Subscriber")
                        .WithMany("TrackedPosts")
                        .HasForeignKey("SubscriberDid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("AltTextBot.Domain.Entities.Subscriber", b =>
                {
                    b.Navigation("TrackedPosts");
                });

            modelBuilder.Entity("AltTextBot.Domain.Entities.TrackedPost", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
